export const FETCH_PRODUCTS = "FETCH_PRODUCTS";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";

export const REMOVE_PRODUCT_FROM_CART = "DELETE_PRODUCT_FROM_CART";

export const MODIFY_PRODUCT_QUANTITY_IN_CART = "MODIFY_PRODUCT_QUANTITY_IN_CART";